apiVersion: v1
kind: Secret
metadata:
  name: mysql
stringData:
  mysql-password: n2P/js1Jucn6aq2+plVwghdyAs0D7x8Zd176eOlmOzo=  # Replace with your desired password

#PASSWORD=$(openssl rand -base64 32)
#echo $PASSWORD
